version: '3'

services:
  db:
    image: postgres:13-alpine
    container_name: test_db
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    env_file:
      - ./db.env
    ports:
      - 5432:5432

  redis:
    image: redis:6-alpine
    hostname: redis
    volumes:
      - "./data/redisdata:/data"
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.8-alpine
    hostname: rabbitmq
    volumes:
      - "./data/rabbitmq:/data"
    env_file:
      - ./rabbitmq.env
    ports:
      - 5672:5672
      - 15672:15672