# Generated by Django 3.1.1 on 2020-09-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('status', models.CharField(choices=[('EV', 'Решение проверяется'), ('CR', 'Решение верное'), ('WR', 'Решение неверное')], default='EV', max_length=2, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created datetime')),
            ],
            options={
                'verbose_name': 'Decision',
                'verbose_name_plural': 'Decisions',
                'db_table': 'decisions',
            },
        ),
    ]
